README.md edited
NDCLab/social-context-dataset pull request #14
Opened 2021-12-27 22:26 UTC by emach039

@jessb0t Changes to the readme file! I'll be adding the new members eventually once they're completely onboarded and working on the project :)

2022-02-09 22:36 UTC, jessb0t commented
Thank you so much for updating this readme, @emach039 !  I made some line-by-line suggestions!

2022-02-09 23:04 UTC, jessb0t requested changes

2022-02-23 16:47 UTC, emach039 reviewed
Will make necessary edits!

2022-02-23 18:00 UTC, emach039 commented on README.md
> +**Data analysis and processing** (Release 1): anticipated Q2 2022
Noted!

2022-02-23 18:00 UTC, emach039 commented on README.md
> +**Paper ready-for-submission** (Release 2): anticipated Q3 2022
Noted!

2022-03-02 16:02 UTC, jessb0t commented
@emach039 It looks like you integrated these changes over on the `dev-contributing` branch, so I'm going to proceed with merging this branch in (and then changes from `dev-contributing` will overwrite).

2022-03-02 16:02 UTC, jessb0t approved these changes

2022-03-02 16:02 UTC, merged